version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=ohmyfood
      - DB_PASSWORD=ohmyfood
      - DB_NAME=ohmyfood

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ohmyfood
      - MYSQL_USER=ohmyfood
      - MYSQL_PASSWORD=ohmyfood
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 